import { Download, FileJson, FileText, Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
  DropdownMenuLabel,
} from '@/components/ui/dropdown-menu';
import { IOCInfo } from '@/lib/ioc-detection';
import { LookupSource } from '@/lib/lookup-sources';
import { toast } from 'sonner';

interface ExportMenuProps {
  iocInfo: IOCInfo;
  sources: LookupSource[];
}

export function ExportMenu({ iocInfo, sources }: ExportMenuProps) {
  const generateMarkdown = () => {
    const now = new Date().toISOString();
    let md = `# IOC Investigation Report\n\n`;
    md += `**Generated:** ${now}\n\n`;
    md += `## Indicator Details\n\n`;
    md += `| Field | Value |\n|-------|-------|\n`;
    md += `| Type | ${iocInfo.type.toUpperCase()} |\n`;
    if (iocInfo.hashType) md += `| Hash Type | ${iocInfo.hashType.toUpperCase()} |\n`;
    md += `| Value (Normal) | \`${iocInfo.value}\` |\n`;
    md += `| Value (Defanged) | \`${iocInfo.defanged}\` |\n\n`;
    md += `## Lookup Sources (${sources.length})\n\n`;
    sources.forEach((source, i) => {
      md += `${i + 1}. **${source.name}** - [${source.category}](${source.getUrl(iocInfo.value)})\n`;
    });
    md += `\n---\n*Generated by SOC Analyst Toolkit*\n`;
    return md;
  };

  const generateJSON = () => {
    return JSON.stringify({
      report: {
        generated: new Date().toISOString(),
        tool: 'SOC Analyst Toolkit',
      },
      indicator: {
        type: iocInfo.type,
        hashType: iocInfo.hashType || null,
        value: iocInfo.value,
        defanged: iocInfo.defanged,
      },
      sources: sources.map(s => ({
        name: s.name,
        category: s.category,
        url: s.getUrl(iocInfo.value),
      })),
    }, null, 2);
  };

  const generateTicketFormat = () => {
    let text = `=== IOC Investigation ===\n`;
    text += `Timestamp: ${new Date().toISOString()}\n\n`;
    text += `[INDICATOR]\n`;
    text += `Type: ${iocInfo.type.toUpperCase()}${iocInfo.hashType ? ` (${iocInfo.hashType.toUpperCase()})` : ''}\n`;
    text += `Value: ${iocInfo.value}\n`;
    text += `Defanged: ${iocInfo.defanged}\n\n`;
    text += `[LOOKUP URLS]\n`;
    sources.forEach((source, i) => {
      text += `${i + 1}. ${source.name}: ${source.getUrl(iocInfo.value)}\n`;
    });
    text += `\n=== End Report ===\n`;
    return text;
  };

  const handleExportMarkdown = () => {
    const md = generateMarkdown();
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ioc-report-${iocInfo.type}-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Exported as Markdown');
  };

  const handleExportJSON = () => {
    const json = generateJSON();
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ioc-report-${iocInfo.type}-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Exported as JSON');
  };

  const handleCopyTicket = () => {
    navigator.clipboard.writeText(generateTicketFormat());
    toast.success('Copied ticket format to clipboard');
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdown());
    toast.success('Copied Markdown to clipboard');
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="lg">
          <Download className="w-4 h-4 mr-2" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-56">
        <DropdownMenuLabel className="text-xs font-mono text-muted-foreground">
          DOWNLOAD
        </DropdownMenuLabel>
        <DropdownMenuItem onClick={handleExportMarkdown} className="cursor-pointer">
          <FileText className="w-4 h-4 mr-2" />
          Download Markdown (.md)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleExportJSON} className="cursor-pointer">
          <FileJson className="w-4 h-4 mr-2" />
          Download JSON (.json)
        </DropdownMenuItem>
        <DropdownMenuSeparator />
        <DropdownMenuLabel className="text-xs font-mono text-muted-foreground">
          COPY TO CLIPBOARD
        </DropdownMenuLabel>
        <DropdownMenuItem onClick={handleCopyMarkdown} className="cursor-pointer">
          <Copy className="w-4 h-4 mr-2" />
          Copy as Markdown
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleCopyTicket} className="cursor-pointer">
          <Copy className="w-4 h-4 mr-2" />
          Copy Ticket Format
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
